<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import defaultAttributes from './default-attributes.js';
  import { resolvePixelGeometry } from './pixel-stroke.js';
  import { hasA11yProp } from './utils/hasA11yProp.js';
  import type { IconProps } from './types.js';

  let {
    name,
    color = 'currentColor',
    size = 24,
    strokeWidth = 2,
    absoluteStrokeWidth = false,
    pixelGap = 0,
    iconPixels = [],
    children,
    title,
    ...props
  }: IconProps = $props();

  const pixelGeometry = $derived(resolvePixelGeometry({ size, strokeWidth, absoluteStrokeWidth, pixelGap }));
  const pixelSize = $derived(pixelGeometry.pixelSize);
  const pixelInset = $derived(pixelGeometry.pixelInset);
</script>

<svg
  {...defaultAttributes}
  {...(!children && !title && !hasA11yProp(props) && { 'aria-hidden': 'true' })}
  {...props}
  width={size}
  height={size}
  class={['pxicons-icon lucide-icon lucide', name && ('lucide-' + name), name && ('pxicons-' + name), props.class]}
  shape-rendering="crispEdges"
>
  {#if title}
    <title>{title}</title>
  {/if}

  <g fill={color}>
    {#each iconPixels as [x, y]}
      <rect x={x + pixelInset} y={y + pixelInset} width={pixelSize} height={pixelSize} />
    {/each}
  </g>

  {@render children?.()}
</svg>
