<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import defaultAttributes from './default-attributes.js';
  import { resolveOptimizedPathData, normalizeRenderMode, normalizeShape } from './pixel-path.js';
  import { resolvePixelGeometry } from './pixel-stroke.js';
  import { hasA11yProp } from './utils/hasA11yProp.js';
  import type { IconProps } from './types.js';

  let {
    name,
    color = 'currentColor',
    size = 24,
    strokeWidth = 2,
    absoluteStrokeWidth = false,
    pixelGap = 0,
    shape = 'square',
    renderMode = 'auto',
    iconPixels = [],
    iconRects = [],
    children,
    title,
    ...props
  }: IconProps = $props();

  const pixelGeometry = $derived(resolvePixelGeometry({ size, strokeWidth, absoluteStrokeWidth, pixelGap }));
  const pixelSize = $derived(pixelGeometry.pixelSize);
  const pixelInset = $derived(pixelGeometry.pixelInset);
  const normalizedShape = $derived(normalizeShape(shape));
  const normalizedRenderMode = $derived(normalizeRenderMode(renderMode));
  const roundedCornerRadius = $derived(Number(Math.min(0.24, Math.max(0, pixelSize / 2)).toFixed(3)));
  const optimizedPathData = $derived(
    resolveOptimizedPathData({
      iconPixels,
      iconRects,
      shape: normalizedShape,
      pixelSize,
      pixelInset
    })
  );
  const canRenderOptimized = $derived(optimizedPathData !== null);
  const shouldRenderOptimized = $derived(
    normalizedRenderMode !== 'raw' && canRenderOptimized
  );
</script>

<svg
  {...defaultAttributes}
  {...(!children && !title && !hasA11yProp(props) && { 'aria-hidden': 'true' })}
  {...props}
  width={size}
  height={size}
  class={['pxicons-icon lucide-icon lucide', name && ('lucide-' + name), name && ('pxicons-' + name), props.class]}
  shape-rendering="crispEdges"
>
  {#if title}
    <title>{title}</title>
  {/if}

  <g fill={color}>
    {#if shouldRenderOptimized}
      <path d={optimizedPathData ?? ''} />
    {:else if normalizedShape === 'circle'}
      {#each iconPixels as [x, y]}
        <circle
          cx={x + pixelInset + pixelSize / 2}
          cy={y + pixelInset + pixelSize / 2}
          r={pixelSize / 2}
        />
      {/each}
    {:else if normalizedShape === 'rounded'}
      {#each iconPixels as [x, y]}
        <rect
          x={x + pixelInset}
          y={y + pixelInset}
          width={pixelSize}
          height={pixelSize}
          rx={roundedCornerRadius}
          ry={roundedCornerRadius}
        />
      {/each}
    {:else}
      {#each iconPixels as [x, y]}
        <rect x={x + pixelInset} y={y + pixelInset} width={pixelSize} height={pixelSize} />
      {/each}
    {/if}
  </g>

  {@render children?.()}
</svg>
