// This file is auto-generated by scripts/generate-lucide.mjs.

export * from './icons/index.js';
export * as icons from './icons/index.js';
export { default as defaultAttributes } from './default-attributes.js';
export { default as Icon } from './Icon.svelte';
export { resolvePixelGeometry } from './pixel-stroke.js';
export type { IconEvents, IconProps, IconSlots, IconPixels, PixelCell } from './types.js';
