// This file is auto-generated by scripts/generate-lucide.mjs.

import type { IconPixels, IconRects, IconRenderMode, PixelShape } from './types.js';

const optimizedPathCache = new WeakMap<IconPixels, Map<string, string>>();

function formatNumber(value: number): string {
  const rounded = Math.round(value * 1000) / 1000;

  if (Number.isInteger(rounded)) {
    return String(rounded);
  }

  return String(rounded)
    .replace(/\.0+$/, '')
    .replace(/(\.\d*?)0+$/, '$1');
}

function createSquareSubpath(x: number, y: number, width: number, height = width): string {
  const px = formatNumber(x);
  const py = formatNumber(y);
  const widthText = formatNumber(width);
  const heightText = formatNumber(height);

  return `M${px} ${py}h${widthText}v${heightText}h-${widthText}Z`;
}

function createCircleSubpath(x: number, y: number, size: number): string {
  const radius = size / 2;
  const centerX = x + radius;
  const centerY = y + radius;
  const diameter = radius * 2;

  return `M${formatNumber(centerX)} ${formatNumber(centerY - radius)}a${formatNumber(radius)} ${formatNumber(radius)} 0 1 0 0 ${formatNumber(diameter)}a${formatNumber(radius)} ${formatNumber(radius)} 0 1 0 0 -${formatNumber(diameter)}Z`;
}

function createRoundedSubpath(x: number, y: number, size: number): string {
  const radius = Math.min(0.24, size / 2);

  if (radius <= 0) {
    return createSquareSubpath(x, y, size);
  }

  const right = x + size;
  const bottom = y + size;

  return [
    `M${formatNumber(x + radius)} ${formatNumber(y)}`,
    `H${formatNumber(right - radius)}`,
    `A${formatNumber(radius)} ${formatNumber(radius)} 0 0 1 ${formatNumber(right)} ${formatNumber(y + radius)}`,
    `V${formatNumber(bottom - radius)}`,
    `A${formatNumber(radius)} ${formatNumber(radius)} 0 0 1 ${formatNumber(right - radius)} ${formatNumber(bottom)}`,
    `H${formatNumber(x + radius)}`,
    `A${formatNumber(radius)} ${formatNumber(radius)} 0 0 1 ${formatNumber(x)} ${formatNumber(bottom - radius)}`,
    `V${formatNumber(y + radius)}`,
    `A${formatNumber(radius)} ${formatNumber(radius)} 0 0 1 ${formatNumber(x + radius)} ${formatNumber(y)}Z`
  ].join('');
}

export function normalizeShape(shape: PixelShape | string | undefined): PixelShape {
  if (shape === 'circle' || shape === 'rounded') {
    return shape;
  }

  return 'square';
}

export function normalizeRenderMode(mode: IconRenderMode | string | undefined): IconRenderMode {
  if (mode === 'raw' || mode === 'optimized') {
    return mode;
  }

  return 'auto';
}

function getCacheMap(iconPixels: IconPixels): Map<string, string> {
  const cached = optimizedPathCache.get(iconPixels);

  if (cached) {
    return cached;
  }

  const next = new Map<string, string>();
  optimizedPathCache.set(iconPixels, next);
  return next;
}

function createSquarePathFromRuns(iconRects: IconRects, pixelSize: number, pixelInset: number): string {
  const segments = [];

  for (const [x, y, width, height] of iconRects) {
    const runX = x + pixelInset;
    const runY = y + pixelInset;
    const runWidth = (width - 1) + pixelSize;
    const runHeight = (height - 1) + pixelSize;

    segments.push(createSquareSubpath(runX, runY, runWidth, runHeight));
  }

  return segments.join('');
}

function createPerPixelPath(iconPixels: IconPixels, shape: PixelShape, pixelSize: number, pixelInset: number): string {
  const segments = [];

  for (const [x, y] of iconPixels) {
    const px = x + pixelInset;
    const py = y + pixelInset;

    if (shape === 'circle') {
      segments.push(createCircleSubpath(px, py, pixelSize));
      continue;
    }

    if (shape === 'rounded') {
      segments.push(createRoundedSubpath(px, py, pixelSize));
      continue;
    }

    segments.push(createSquareSubpath(px, py, pixelSize));
  }

  return segments.join('');
}

export interface OptimizedPathOptions {
  iconPixels: IconPixels;
  iconRects: IconRects;
  shape: PixelShape;
  pixelSize: number;
  pixelInset: number;
}

export function resolveOptimizedPathData(options: OptimizedPathOptions): string | null {
  const { iconPixels, iconRects, pixelSize, pixelInset } = options;

  if (iconPixels.length === 0) {
    return '';
  }

  if (!Number.isFinite(pixelSize) || !Number.isFinite(pixelInset) || pixelSize <= 0) {
    return null;
  }

  const shape = normalizeShape(options.shape);
  const key = [shape, formatNumber(pixelSize), formatNumber(pixelInset)].join('|');
  const cache = getCacheMap(iconPixels);
  const cachedPath = cache.get(key);

  if (cachedPath !== undefined) {
    return cachedPath;
  }

  const canUseRuns = shape === 'square' && pixelSize >= 1 && iconRects.length > 0;
  const pathData = canUseRuns
    ? createSquarePathFromRuns(iconRects, pixelSize, pixelInset)
    : createPerPixelPath(iconPixels, shape, pixelSize, pixelInset);

  cache.set(key, pathData);
  return pathData;
}
