// This file is auto-generated by scripts/generate-lucide.mjs.

export {
  normalizeRenderMode,
  normalizeShape,
  resolveOptimizedPathData
} from '@pxicons/lucide-core';
export type { OptimizedPathOptions } from '@pxicons/lucide-core';
