// This file is auto-generated by scripts/generate-lucide.mjs.

export { resolvePixelGeometry } from '@pxicons/lucide/_core';
export type { PixelGeometry, PixelGeometryOptions } from '@pxicons/lucide/_core';
