// This file is auto-generated by scripts/generate-lucide.mjs.

import type { Snippet } from 'svelte';
import type { SVGAttributes, SvelteHTMLElements } from 'svelte/elements';

export type PixelCell = readonly [number, number];
export type IconPixels = readonly PixelCell[];

export interface IconProps extends SVGAttributes<SVGSVGElement> {
  name?: string;
  color?: string;
  size?: number | string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
  iconPixels?: IconPixels;
  children?: Snippet;
  title?: string;
}

export type IconEvents = {
  [evt: string]: CustomEvent<any>;
};

export type IconSlots = {
  default: {};
};

export type PixelTag = keyof SvelteHTMLElements;
