import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { generateLucideEntries } from '../../../../tools/lucide-generator/index.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageDir = path.resolve(__dirname, '..');
const generatedDir = path.join(packageDir, 'src/generated');
const generatedIconsDir = path.join(generatedDir, 'icons');
const lucideDir = packageDir;

const GENERATED_HEADER = '// This file is auto-generated by scripts/generate-runtime.mjs.\n';
const RESERVED_WORDS = new Set([
  'await',
  'break',
  'case',
  'catch',
  'class',
  'const',
  'continue',
  'debugger',
  'default',
  'delete',
  'do',
  'else',
  'enum',
  'export',
  'extends',
  'false',
  'finally',
  'for',
  'function',
  'if',
  'implements',
  'import',
  'in',
  'instanceof',
  'interface',
  'let',
  'new',
  'null',
  'package',
  'private',
  'protected',
  'public',
  'return',
  'static',
  'super',
  'switch',
  'this',
  'throw',
  'true',
  'try',
  'typeof',
  'var',
  'void',
  'while',
  'with',
  'yield'
]);

async function ensureEmptyDirectory(dirPath) {
  await fs.rm(dirPath, { recursive: true, force: true });
  await fs.mkdir(dirPath, { recursive: true });
}

async function writeFile(filePath, content) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

function createIconDefinitionFile(entry) {
  const iconData = {
    id: entry.iconId,
    library: 'lucide',
    name: entry.iconName,
    tags: entry.tags,
    viewBox: entry.viewBox,
    iconPixels: entry.iconPixels,
    iconRects: entry.iconRects
  };

  return `${GENERATED_HEADER}
import type { LucideIconDefinition } from '@pxicons/lucide-core';

const icon = ${JSON.stringify(iconData)} as const satisfies LucideIconDefinition;

export default icon;
`;
}

function createIconsIndexFile(entries) {
  const lines = entries.map((entry) => `export { default as ${entry.exportName} } from './${entry.iconId}.js';`);

  return `${GENERATED_HEADER}
${lines.join('\n')}
`;
}

function createIconsRegistryFile(entries) {
  const localNameCounts = new Map();
  const bindings = entries.map((entry) => {
    const safeBase = entry.exportName
      .replace(/[^A-Za-z0-9_$]/g, '_')
      .replace(/^[^A-Za-z_$]/, '_$&');
    const reservedSafeBase = RESERVED_WORDS.has(safeBase) ? `${safeBase}Icon` : safeBase;
    const previousCount = localNameCounts.get(reservedSafeBase) ?? 0;
    const nextCount = previousCount + 1;
    localNameCounts.set(reservedSafeBase, nextCount);
    const localName = previousCount === 0 ? reservedSafeBase : `${reservedSafeBase}${nextCount}`;

    return {
      exportName: entry.exportName,
      localName
    };
  });

  const importSpecifiers = bindings
    .map(({ exportName, localName }) =>
      exportName === localName ? `  ${exportName}` : `  ${exportName} as ${localName}`
    )
    .join(',\n');

  return `${GENERATED_HEADER}
import type { LucideIconDefinition } from '@pxicons/lucide-core';
import {
${importSpecifiers}
} from './index.js';

export const icons: Readonly<Record<string, LucideIconDefinition>> = Object.freeze({
${bindings.map(({ exportName, localName }) => `  ${JSON.stringify(exportName)}: ${localName},`).join('\n')}
});

const iconValues = Object.values(icons) as readonly LucideIconDefinition[];

export const iconsById: Readonly<Record<string, LucideIconDefinition>> = Object.freeze(
  Object.fromEntries(iconValues.map((icon) => [icon.id, icon]))
);
`;
}

async function main() {
  const entries = await generateLucideEntries(lucideDir);

  await ensureEmptyDirectory(generatedIconsDir);

  for (const entry of entries) {
    await writeFile(
      path.join(generatedIconsDir, `${entry.iconId}.ts`),
      createIconDefinitionFile(entry)
    );
  }

  await writeFile(path.join(generatedIconsDir, 'index.ts'), createIconsIndexFile(entries));
  await writeFile(path.join(generatedIconsDir, 'registry.ts'), createIconsRegistryFile(entries));

  console.log(`Generated ${entries.length} vanilla icon definitions.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
