// This file is auto-generated by scripts/generate-lucide-react.mjs.

const defaultAttributes = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'none'
} as const;

export default defaultAttributes;
