// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef, type ReactNode } from 'react';

import { hasA11yProp, resolveIconRenderModel, type PixelShape } from '@pxicons/lucide/_core';

import defaultAttributes from './default-attributes.js';
import type { IconProps } from './types.js';

function formatNumber(value: number): string {
  const rounded = Math.round(value * 1000) / 1000;

  if (Number.isInteger(rounded)) {
    return String(rounded);
  }

  return String(rounded)
    .replace(/\.0+$/, '')
    .replace(/(\.\d*?)0+$/, '$1');
}

function joinClasses(...values: Array<string | undefined>): string {
  const classSet = new Set<string>();

  for (const value of values) {
    if (!value) {
      continue;
    }

    for (const token of value.split(/\s+/)) {
      const trimmed = token.trim();

      if (trimmed.length > 0) {
        classSet.add(trimmed);
      }
    }
  }

  return [...classSet].join(' ');
}

function buildRawPrimitiveNodes(
  shape: PixelShape,
  iconPixels: readonly (readonly [number, number])[],
  pixelSize: number,
  pixelInset: number,
  roundedCornerRadius: number
): ReactNode[] {
  if (shape === 'circle') {
    return iconPixels.map(([x, y], index) => {
      const cx = x + pixelInset + pixelSize / 2;
      const cy = y + pixelInset + pixelSize / 2;

      return (
        <circle
          key={index}
          cx={formatNumber(cx)}
          cy={formatNumber(cy)}
          r={formatNumber(pixelSize / 2)}
        />
      );
    });
  }

  if (shape === 'rounded') {
    return iconPixels.map(([x, y], index) => {
      const px = x + pixelInset;
      const py = y + pixelInset;

      return (
        <rect
          key={index}
          x={formatNumber(px)}
          y={formatNumber(py)}
          width={formatNumber(pixelSize)}
          height={formatNumber(pixelSize)}
          rx={formatNumber(roundedCornerRadius)}
          ry={formatNumber(roundedCornerRadius)}
        />
      );
    });
  }

  return iconPixels.map(([x, y], index) => {
    const px = x + pixelInset;
    const py = y + pixelInset;

    return (
      <rect
        key={index}
        x={formatNumber(px)}
        y={formatNumber(py)}
        width={formatNumber(pixelSize)}
        height={formatNumber(pixelSize)}
      />
    );
  });
}

const Icon = forwardRef<SVGSVGElement, IconProps>((props, ref) => {
  const {
    name,
    color = 'currentColor',
    size = 24,
    strokeWidth = 2,
    absoluteStrokeWidth = false,
    shape = 'square',
    renderMode = 'auto',
    iconPixels = [],
    iconRects = [],
    className,
    children,
    title,
    ...rest
  } = props;

  const renderModel = resolveIconRenderModel({
    iconPixels,
    iconRects,
    size,
    strokeWidth,
    absoluteStrokeWidth,
    shape,
    renderMode
  });

  const combinedClassName = joinClasses(
    'pxicons-icon lucide-icon lucide',
    name ? 'lucide-' + name : undefined,
    name ? 'pxicons-' + name : undefined,
    className
  );

  const svgProps: IconProps = {
    ...defaultAttributes,
    ...rest,
    width: size,
    height: size,
    className: combinedClassName,
    shapeRendering: 'crispEdges'
  };

  if (!title && !children && !hasA11yProp(rest as Record<string, unknown>)) {
    svgProps['aria-hidden'] = 'true';
  }

  return (
    <svg ref={ref} {...svgProps}>
      {title ? <title>{title}</title> : null}
      <g fill={color}>
        {renderModel.shouldRenderOptimized ? (
          <path d={renderModel.optimizedPathData ?? ''} />
        ) : (
          buildRawPrimitiveNodes(
            renderModel.normalizedShape,
            iconPixels,
            renderModel.pixelSize,
            renderModel.pixelInset,
            renderModel.roundedCornerRadius
          )
        )}
      </g>
      {children}
    </svg>
  );
});

Icon.displayName = 'Icon';

export default Icon;
