// This file is auto-generated by scripts/generate-lucide-react.mjs.

export * from './icons/index.js';
export * as icons from './icons/index.js';
export { default as Icon } from './Icon.js';
export type { IconProps } from './types.js';
export type { IconRenderMode, PixelShape } from '@pxicons/lucide-core';
