// This file is auto-generated by scripts/generate-lucide-react.mjs.

import type { SVGProps } from 'react';
import type { IconPixels, IconRects, IconRenderMode, PixelShape } from '@pxicons/lucide/_core';

export interface IconProps extends Omit<SVGProps<SVGSVGElement>, 'color'> {
  name?: string;
  color?: string;
  size?: number | string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
  shape?: PixelShape | string;
  renderMode?: IconRenderMode | string;
  iconPixels?: IconPixels;
  iconRects?: IconRects;
  title?: string;
}
