// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[11,3],[12,3],[10,4],[11,4],[12,4],[13,4],[9,5],[10,5],[11,5],[12,5],[13,5],[14,5],[8,6],[9,6],[10,6],[13,6],[14,6],[15,6],[7,7],[8,7],[9,7],[14,7],[15,7],[16,7],[6,8],[7,8],[8,8],[15,8],[16,8],[17,8],[6,9],[7,9],[16,9],[17,9],[6,14],[7,14],[16,14],[17,14],[6,15],[7,15],[8,15],[15,15],[16,15],[17,15],[7,16],[8,16],[9,16],[14,16],[15,16],[16,16],[8,17],[9,17],[10,17],[13,17],[14,17],[15,17],[9,18],[10,18],[11,18],[12,18],[13,18],[14,18],[10,19],[11,19],[12,19],[13,19],[11,20],[12,20]] as const;
const iconRects = [[11,3,2,1],[10,4,4,1],[9,5,6,1],[8,6,3,1],[13,6,3,1],[7,7,3,1],[14,7,3,1],[6,8,3,1],[15,8,3,1],[6,9,2,1],[16,9,2,1],[6,14,2,1],[16,14,2,1],[6,15,3,1],[15,15,3,1],[7,16,3,1],[14,16,3,1],[8,17,3,1],[13,17,3,1],[9,18,6,1],[10,19,4,1],[11,20,2,1]] as const;

const ChevronsUpDown = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="chevrons-up-down"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

ChevronsUpDown.displayName = 'ChevronsUpDown';

export default ChevronsUpDown;
