// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[14,5],[15,5],[13,6],[14,6],[15,6],[12,7],[13,7],[14,7],[11,8],[12,8],[13,8],[10,9],[11,9],[12,9],[9,10],[10,10],[11,10],[8,11],[9,11],[10,11],[8,12],[9,12],[10,12],[9,13],[10,13],[11,13],[10,14],[11,14],[12,14],[11,15],[12,15],[13,15],[12,16],[13,16],[14,16],[13,17],[14,17],[15,17],[14,18],[15,18]] as const;
const iconRects = [[14,5,2,1],[13,6,3,1],[12,7,3,1],[11,8,3,1],[10,9,3,1],[9,10,3,1],[8,11,3,1],[8,12,3,1],[9,13,3,1],[10,14,3,1],[11,15,3,1],[12,16,3,1],[13,17,3,1],[14,18,2,1]] as const;

const ChevronLeft = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="chevron-left"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

ChevronLeft.displayName = 'ChevronLeft';

export default ChevronLeft;
