// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[11,8],[12,8],[10,9],[11,9],[12,9],[13,9],[9,10],[10,10],[11,10],[12,10],[13,10],[14,10],[8,11],[9,11],[10,11],[13,11],[14,11],[15,11],[7,12],[8,12],[9,12],[14,12],[15,12],[16,12],[6,13],[7,13],[8,13],[15,13],[16,13],[17,13],[5,14],[6,14],[7,14],[16,14],[17,14],[18,14],[5,15],[6,15],[17,15],[18,15]] as const;
const iconRects = [[11,8,2,1],[10,9,4,1],[9,10,6,1],[8,11,3,1],[13,11,3,1],[7,12,3,1],[14,12,3,1],[6,13,3,1],[15,13,3,1],[5,14,3,1],[16,14,3,1],[5,15,2,1],[17,15,2,1]] as const;

const ChevronUp = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="chevron-up"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

ChevronUp.displayName = 'ChevronUp';

export default ChevronUp;
