// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[5,8],[6,8],[17,8],[18,8],[5,9],[6,9],[7,9],[16,9],[17,9],[18,9],[6,10],[7,10],[8,10],[15,10],[16,10],[17,10],[7,11],[8,11],[9,11],[14,11],[15,11],[16,11],[8,12],[9,12],[10,12],[13,12],[14,12],[15,12],[9,13],[10,13],[11,13],[12,13],[13,13],[14,13],[10,14],[11,14],[12,14],[13,14],[11,15],[12,15]] as const;
const iconRects = [[5,8,2,1],[17,8,2,1],[5,9,3,1],[16,9,3,1],[6,10,3,1],[15,10,3,1],[7,11,3,1],[14,11,3,1],[8,12,3,1],[13,12,3,1],[9,13,6,1],[10,14,4,1],[11,15,2,1]] as const;

const ChevronDown = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="chevron-down"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

ChevronDown.displayName = 'ChevronDown';

export default ChevronDown;
