// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[11,4],[12,4],[10,5],[11,5],[12,5],[13,5],[10,6],[11,6],[12,6],[13,6],[11,7],[12,7],[4,11],[5,11],[6,11],[7,11],[8,11],[9,11],[10,11],[11,11],[12,11],[13,11],[14,11],[15,11],[16,11],[17,11],[18,11],[19,11],[4,12],[5,12],[6,12],[7,12],[8,12],[9,12],[10,12],[11,12],[12,12],[13,12],[14,12],[15,12],[16,12],[17,12],[18,12],[19,12],[11,16],[12,16],[10,17],[11,17],[12,17],[13,17],[10,18],[11,18],[12,18],[13,18],[11,19],[12,19]] as const;
const iconRects = [[11,4,2,1],[10,5,4,1],[10,6,4,1],[11,7,2,1],[4,11,16,1],[4,12,16,1],[11,16,2,1],[10,17,4,1],[10,18,4,1],[11,19,2,1]] as const;

const Divide = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="divide"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

Divide.displayName = 'Divide';

export default Divide;
