// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[11,10],[12,10],[10,11],[11,11],[12,11],[13,11],[10,12],[11,12],[12,12],[13,12],[11,13],[12,13],[13,13]] as const;
const iconRects = [[11,10,2,1],[10,11,4,1],[10,12,4,1],[11,13,3,1]] as const;

const Dot = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="dot"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

Dot.displayName = 'Dot';

export default Dot;
