// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[4,10],[5,10],[11,10],[12,10],[18,10],[19,10],[3,11],[4,11],[5,11],[6,11],[10,11],[11,11],[12,11],[13,11],[17,11],[18,11],[19,11],[20,11],[3,12],[4,12],[5,12],[6,12],[10,12],[11,12],[12,12],[13,12],[17,12],[18,12],[19,12],[20,12],[4,13],[5,13],[11,13],[12,13],[18,13],[19,13]] as const;
const iconRects = [[4,10,2,1],[11,10,2,1],[18,10,2,1],[3,11,4,1],[10,11,4,1],[17,11,4,1],[3,12,4,1],[10,12,4,1],[17,12,4,1],[4,13,2,1],[11,13,2,1],[18,13,2,1]] as const;

const Ellipsis = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="ellipsis"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

Ellipsis.displayName = 'Ellipsis';

export default Ellipsis;
