// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[11,3],[12,3],[10,4],[11,4],[12,4],[13,4],[10,5],[11,5],[12,5],[13,5],[11,6],[12,6],[11,10],[12,10],[10,11],[11,11],[12,11],[13,11],[10,12],[11,12],[12,12],[13,12],[11,13],[12,13],[11,17],[12,17],[10,18],[11,18],[12,18],[13,18],[10,19],[11,19],[12,19],[13,19],[11,20],[12,20]] as const;
const iconRects = [[11,3,2,1],[10,4,4,1],[10,5,4,1],[11,6,2,1],[11,10,2,1],[10,11,4,1],[10,12,4,1],[11,13,2,1],[11,17,2,1],[10,18,4,1],[10,19,4,1],[11,20,2,1]] as const;

const EllipsisVertical = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="ellipsis-vertical"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

EllipsisVertical.displayName = 'EllipsisVertical';

export default EllipsisVertical;
