// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[10,8],[11,8],[12,8],[13,8],[9,9],[10,9],[11,9],[12,9],[13,9],[14,9],[8,10],[9,10],[10,10],[13,10],[14,10],[15,10],[2,11],[3,11],[4,11],[5,11],[6,11],[7,11],[8,11],[9,11],[14,11],[15,11],[16,11],[17,11],[18,11],[19,11],[20,11],[21,11],[2,12],[3,12],[4,12],[5,12],[6,12],[7,12],[8,12],[9,12],[14,12],[15,12],[16,12],[17,12],[18,12],[19,12],[20,12],[21,12],[8,13],[9,13],[10,13],[13,13],[14,13],[15,13],[9,14],[10,14],[11,14],[12,14],[13,14],[14,14],[10,15],[11,15],[12,15],[13,15]] as const;
const iconRects = [[10,8,4,1],[9,9,6,1],[8,10,3,1],[13,10,3,1],[2,11,8,1],[14,11,8,1],[2,12,8,1],[14,12,8,1],[8,13,3,1],[13,13,3,1],[9,14,6,1],[10,15,4,1]] as const;

const GitCommitHorizontal = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="git-commit-horizontal"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

GitCommitHorizontal.displayName = 'GitCommitHorizontal';

export default GitCommitHorizontal;
