// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[6,15],[7,15],[6,16],[7,16],[6,17],[7,17],[6,18],[7,18],[1,19],[2,19],[6,19],[7,19],[1,20],[2,20],[6,20],[7,20]] as const;
const iconRects = [[6,15,2,1],[6,16,2,1],[6,17,2,1],[6,18,2,1],[1,19,2,1],[6,19,2,1],[1,20,2,1],[6,20,2,1]] as const;

const SignalLow = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="signal-low"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

SignalLow.displayName = 'SignalLow';

export default SignalLow;
