// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[1,19],[2,19],[1,20],[2,20]] as const;
const iconRects = [[1,19,2,1],[1,20,2,1]] as const;

const SignalZero = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="signal-zero"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

SignalZero.displayName = 'SignalZero';

export default SignalZero;
