// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[1,16],[2,16],[21,16],[22,16],[1,17],[2,17],[3,17],[20,17],[21,17],[22,17],[1,18],[2,18],[3,18],[4,18],[5,18],[6,18],[7,18],[8,18],[9,18],[10,18],[11,18],[12,18],[13,18],[14,18],[15,18],[16,18],[17,18],[18,18],[19,18],[20,18],[21,18],[22,18],[2,19],[3,19],[4,19],[5,19],[6,19],[7,19],[8,19],[9,19],[10,19],[11,19],[12,19],[13,19],[14,19],[15,19],[16,19],[17,19],[18,19],[19,19],[20,19],[21,19]] as const;
const iconRects = [[1,16,2,1],[21,16,2,1],[1,17,3,1],[20,17,3,1],[1,18,22,1],[2,19,20,1]] as const;

const Space = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="space"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

Space.displayName = 'Space';

export default Space;
