// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[3,3],[4,3],[3,4],[4,4],[3,5],[4,5],[3,6],[4,6],[3,7],[4,7],[3,8],[4,8],[3,9],[4,9],[3,10],[4,10],[3,11],[4,11],[3,12],[4,12],[3,13],[4,13],[3,14],[4,14],[3,15],[4,15],[3,16],[4,16],[3,17],[4,17],[3,18],[4,18],[3,19],[4,19],[3,20],[4,20]] as const;
const iconRects = [[3,3,2,1],[3,4,2,1],[3,5,2,1],[3,6,2,1],[3,7,2,1],[3,8,2,1],[3,9,2,1],[3,10,2,1],[3,11,2,1],[3,12,2,1],[3,13,2,1],[3,14,2,1],[3,15,2,1],[3,16,2,1],[3,17,2,1],[3,18,2,1],[3,19,2,1],[3,20,2,1]] as const;

const Tally1 = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="tally-1"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

Tally1.displayName = 'Tally1';

export default Tally1;
