// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[10,14],[11,14],[12,14],[13,14],[8,15],[9,15],[10,15],[11,15],[12,15],[13,15],[14,15],[15,15],[7,16],[8,16],[9,16],[14,16],[15,16],[16,16],[11,19],[12,19],[11,20],[12,20]] as const;
const iconRects = [[10,14,4,1],[8,15,8,1],[7,16,3,1],[14,16,3,1],[11,19,2,1],[11,20,2,1]] as const;

const WifiLow = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="wifi-low"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

WifiLow.displayName = 'WifiLow';

export default WifiLow;
