// This file is auto-generated by scripts/generate-lucide-react.mjs.

import { forwardRef } from 'react';

import Icon from '../Icon.js';
import type { IconProps } from '../types.js';

const iconPixels = [[11,19],[12,19],[11,20],[12,20]] as const;
const iconRects = [[11,19,2,1],[11,20,2,1]] as const;

const WifiZero = forwardRef<SVGSVGElement, IconProps>((props, ref) => (
  <Icon
    ref={ref}
    name="wifi-zero"
    iconPixels={iconPixels}
    iconRects={iconRects}
    {...props}
  />
));

WifiZero.displayName = 'WifiZero';

export default WifiZero;
