// This file is auto-generated by scripts/generate-lucide.mjs.

const A11Y_ATTRIBUTES = [
  'aria-label',
  'aria-labelledby',
  'aria-describedby',
  'role',
  'aria-hidden'
] as const;

export function hasA11yProp(props: Record<string, unknown>): boolean {
  return A11Y_ATTRIBUTES.some((attribute) => {
    const value = props[attribute];

    if (value === undefined || value === null) {
      return false;
    }

    if (typeof value === 'boolean') {
      return value;
    }

    if (typeof value === 'string') {
      return value.trim().length > 0;
    }

    return true;
  });
}
