import { promises as fs } from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageDir = path.resolve(__dirname, '..');
const sourceDir = path.resolve(packageDir, '../../icons/lucide/src');
const outputDir = path.join(packageDir, 'src/lucide');
const iconsOutputDir = path.join(outputDir, 'icons');
const utilsOutputDir = path.join(outputDir, 'utils');

const GENERATED_HEADER = '// This file is auto-generated by scripts/generate-lucide.mjs.\n';

function evaluateTsModule(source, exportName) {
  const module = { exports: {} };
  const context = vm.createContext({ module, exports: module.exports, Object, Array, String, Number, Boolean });
  const script = new vm.Script(`${source}\nmodule.exports = { ${exportName} };`);
  script.runInContext(context);
  return module.exports[exportName];
}

async function loadManifest() {
  const manifestPath = path.join(sourceDir, 'icon-manifest.ts');
  let source = await fs.readFile(manifestPath, 'utf8');

  source = source
    .replace(/export interface[\s\S]*?}\n\n/g, '')
    .replace(/export type[^\n]*\n/g, '')
    .replace(/export const iconManifest\s*:[^=]+=/, 'const iconManifest =');

  const manifest = evaluateTsModule(source, 'iconManifest');

  if (!Array.isArray(manifest)) {
    throw new Error('Could not parse iconManifest from @pxicons/lucide.');
  }

  return manifest;
}

async function loadPixelMap() {
  const pixelMapPath = path.join(sourceDir, 'pixel-map.ts');
  let source = await fs.readFile(pixelMapPath, 'utf8');

  source = source
    .replace(/export type[^\n]*\n/g, '')
    .replace(/export const lucidePixelMap\s*:[^=]+=/, 'const lucidePixelMap =');

  const pixelMap = evaluateTsModule(source, 'lucidePixelMap');

  if (!pixelMap || typeof pixelMap !== 'object') {
    throw new Error('Could not parse lucidePixelMap from @pxicons/lucide.');
  }

  return pixelMap;
}

function toPascalCase(iconId) {
  return iconId
    .split('-')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

function toRectRuns(iconPixels) {
  const rows = new Map();

  for (const cell of iconPixels) {
    const x = Number(cell?.[0]);
    const y = Number(cell?.[1]);

    if (!Number.isInteger(x) || !Number.isInteger(y)) {
      continue;
    }

    const row = rows.get(y);

    if (row) {
      row.push(x);
    } else {
      rows.set(y, [x]);
    }
  }

  const rectRuns = [];
  const sortedRows = [...rows.keys()].sort((a, b) => a - b);

  for (const y of sortedRows) {
    const xs = [...new Set(rows.get(y) ?? [])].sort((a, b) => a - b);

    if (xs.length === 0) {
      continue;
    }

    let startX = xs[0];
    let previousX = xs[0];

    for (let index = 1; index < xs.length; index += 1) {
      const currentX = xs[index];

      if (currentX === previousX + 1) {
        previousX = currentX;
        continue;
      }

      rectRuns.push([startX, y, previousX - startX + 1, 1]);
      startX = currentX;
      previousX = currentX;
    }

    rectRuns.push([startX, y, previousX - startX + 1, 1]);
  }

  return rectRuns;
}

function createTypesFile() {
  return `${GENERATED_HEADER}
import type { Snippet } from 'svelte';
import type { SVGAttributes, SvelteHTMLElements } from 'svelte/elements';

export type PixelCell = readonly [number, number];
export type PixelRect = readonly [number, number, number, number];
export type IconPixels = readonly PixelCell[];
export type IconRects = readonly PixelRect[];
export type PixelShape = 'square' | 'circle' | 'rounded';
export type IconRenderMode = 'auto' | 'raw' | 'optimized';

export interface IconProps extends SVGAttributes<SVGSVGElement> {
  name?: string;
  color?: string;
  size?: number | string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
  pixelGap?: number | string;
  shape?: PixelShape;
  renderMode?: IconRenderMode;
  iconPixels?: IconPixels;
  iconRects?: IconRects;
  children?: Snippet;
  title?: string;
}

export type IconEvents = {
  [evt: string]: CustomEvent<any>;
};

export type IconSlots = {
  default: {};
};

export type PixelTag = keyof SvelteHTMLElements;
`;
}

function createDefaultAttributesFile() {
  return `${GENERATED_HEADER}
const defaultAttributes = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'none'
} as const;

export default defaultAttributes;
`;
}

function createPixelStrokeFile() {
  return `${GENERATED_HEADER}
export interface PixelGeometryOptions {
  size?: number | string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
  pixelGap?: number | string;
}

export interface PixelGeometry {
  pixelSize: number;
  pixelInset: number;
}

export function resolvePixelGeometry(options: PixelGeometryOptions): PixelGeometry {
  const strokeWidth = options.strokeWidth ?? 2;
  const size = options.size ?? 24;
  const absoluteStrokeWidth = options.absoluteStrokeWidth ?? false;
  const pixelGap = options.pixelGap ?? 0;

  const parsedStrokeWidth = Number(strokeWidth);
  const safeStrokeWidth = Number.isFinite(parsedStrokeWidth) ? parsedStrokeWidth : 2;

  const parsedSize = Number(size);
  const hasNumericSize = Number.isFinite(parsedSize) && parsedSize > 0;

  const effectiveStrokeWidth =
    absoluteStrokeWidth && hasNumericSize
      ? (safeStrokeWidth * 24) / parsedSize
      : safeStrokeWidth;

  const parsedPixelGap = Number(pixelGap);
  const safePixelGap = Number.isFinite(parsedPixelGap)
    ? Math.min(0.95, Math.max(0, parsedPixelGap))
    : 0;
  const basePixelSize = Math.max(0.05, effectiveStrokeWidth / 2);
  const pixelSize = Number(Math.min(2, Math.max(0.05, basePixelSize - safePixelGap)).toFixed(3));
  const pixelInset = Number(((1 - pixelSize) / 2).toFixed(3));

  return { pixelSize, pixelInset };
}
`;
}

function createPixelPathFile() {
  return `${GENERATED_HEADER}
import type { IconPixels, IconRects, IconRenderMode, PixelShape } from './types.js';

const optimizedPathCache = new WeakMap<IconPixels, Map<string, string>>();

function formatNumber(value: number): string {
  const rounded = Math.round(value * 1000) / 1000;

  if (Number.isInteger(rounded)) {
    return String(rounded);
  }

  return String(rounded)
    .replace(/\\.0+$/, '')
    .replace(/(\\.\\d*?)0+$/, '$1');
}

function createSquareSubpath(x: number, y: number, width: number, height = width): string {
  const px = formatNumber(x);
  const py = formatNumber(y);
  const widthText = formatNumber(width);
  const heightText = formatNumber(height);

  return \`M\${px} \${py}h\${widthText}v\${heightText}h-\${widthText}Z\`;
}

function createCircleSubpath(x: number, y: number, size: number): string {
  const radius = size / 2;
  const centerX = x + radius;
  const centerY = y + radius;
  const diameter = radius * 2;

  return \`M\${formatNumber(centerX)} \${formatNumber(centerY - radius)}a\${formatNumber(radius)} \${formatNumber(radius)} 0 1 0 0 \${formatNumber(diameter)}a\${formatNumber(radius)} \${formatNumber(radius)} 0 1 0 0 -\${formatNumber(diameter)}Z\`;
}

function createRoundedSubpath(x: number, y: number, size: number): string {
  const radius = Math.min(0.24, size / 2);

  if (radius <= 0) {
    return createSquareSubpath(x, y, size);
  }

  const right = x + size;
  const bottom = y + size;

  return [
    \`M\${formatNumber(x + radius)} \${formatNumber(y)}\`,
    \`H\${formatNumber(right - radius)}\`,
    \`A\${formatNumber(radius)} \${formatNumber(radius)} 0 0 1 \${formatNumber(right)} \${formatNumber(y + radius)}\`,
    \`V\${formatNumber(bottom - radius)}\`,
    \`A\${formatNumber(radius)} \${formatNumber(radius)} 0 0 1 \${formatNumber(right - radius)} \${formatNumber(bottom)}\`,
    \`H\${formatNumber(x + radius)}\`,
    \`A\${formatNumber(radius)} \${formatNumber(radius)} 0 0 1 \${formatNumber(x)} \${formatNumber(bottom - radius)}\`,
    \`V\${formatNumber(y + radius)}\`,
    \`A\${formatNumber(radius)} \${formatNumber(radius)} 0 0 1 \${formatNumber(x + radius)} \${formatNumber(y)}Z\`
  ].join('');
}

export function normalizeShape(shape: PixelShape | string | undefined): PixelShape {
  if (shape === 'circle' || shape === 'rounded') {
    return shape;
  }

  return 'square';
}

export function normalizeRenderMode(mode: IconRenderMode | string | undefined): IconRenderMode {
  if (mode === 'raw' || mode === 'optimized') {
    return mode;
  }

  return 'auto';
}

function getCacheMap(iconPixels: IconPixels): Map<string, string> {
  const cached = optimizedPathCache.get(iconPixels);

  if (cached) {
    return cached;
  }

  const next = new Map<string, string>();
  optimizedPathCache.set(iconPixels, next);
  return next;
}

function createSquarePathFromRuns(iconRects: IconRects, pixelSize: number, pixelInset: number): string {
  const segments = [];

  for (const [x, y, width, height] of iconRects) {
    const runX = x + pixelInset;
    const runY = y + pixelInset;
    const runWidth = (width - 1) + pixelSize;
    const runHeight = (height - 1) + pixelSize;

    segments.push(createSquareSubpath(runX, runY, runWidth, runHeight));
  }

  return segments.join('');
}

function createPerPixelPath(iconPixels: IconPixels, shape: PixelShape, pixelSize: number, pixelInset: number): string {
  const segments = [];

  for (const [x, y] of iconPixels) {
    const px = x + pixelInset;
    const py = y + pixelInset;

    if (shape === 'circle') {
      segments.push(createCircleSubpath(px, py, pixelSize));
      continue;
    }

    if (shape === 'rounded') {
      segments.push(createRoundedSubpath(px, py, pixelSize));
      continue;
    }

    segments.push(createSquareSubpath(px, py, pixelSize));
  }

  return segments.join('');
}

export interface OptimizedPathOptions {
  iconPixels: IconPixels;
  iconRects: IconRects;
  shape: PixelShape;
  pixelSize: number;
  pixelInset: number;
}

export function resolveOptimizedPathData(options: OptimizedPathOptions): string | null {
  const { iconPixels, iconRects, pixelSize, pixelInset } = options;

  if (iconPixels.length === 0) {
    return '';
  }

  if (!Number.isFinite(pixelSize) || !Number.isFinite(pixelInset) || pixelSize <= 0) {
    return null;
  }

  const shape = normalizeShape(options.shape);
  const key = [shape, formatNumber(pixelSize), formatNumber(pixelInset)].join('|');
  const cache = getCacheMap(iconPixels);
  const cachedPath = cache.get(key);

  if (cachedPath !== undefined) {
    return cachedPath;
  }

  const canUseRuns = shape === 'square' && pixelSize >= 1 && iconRects.length > 0;
  const pathData = canUseRuns
    ? createSquarePathFromRuns(iconRects, pixelSize, pixelInset)
    : createPerPixelPath(iconPixels, shape, pixelSize, pixelInset);

  cache.set(key, pathData);
  return pathData;
}
`;
}

function createHasA11yPropFile() {
  return `${GENERATED_HEADER}
const A11Y_ATTRIBUTES = [
  'aria-label',
  'aria-labelledby',
  'aria-describedby',
  'role',
  'aria-hidden'
] as const;

export function hasA11yProp(props: Record<string, unknown>): boolean {
  return A11Y_ATTRIBUTES.some((attribute) => {
    const value = props[attribute];

    if (value === undefined || value === null) {
      return false;
    }

    if (typeof value === 'boolean') {
      return value;
    }

    if (typeof value === 'string') {
      return value.trim().length > 0;
    }

    return true;
  });
}
`;
}

function createIconBaseFile() {
  return `<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import defaultAttributes from './default-attributes.js';
  import { resolveOptimizedPathData, normalizeRenderMode, normalizeShape } from './pixel-path.js';
  import { resolvePixelGeometry } from './pixel-stroke.js';
  import { hasA11yProp } from './utils/hasA11yProp.js';
  import type { IconProps } from './types.js';

  let {
    name,
    color = 'currentColor',
    size = 24,
    strokeWidth = 2,
    absoluteStrokeWidth = false,
    pixelGap = 0,
    shape = 'square',
    renderMode = 'auto',
    iconPixels = [],
    iconRects = [],
    children,
    title,
    ...props
  }: IconProps = $props();

  const pixelGeometry = $derived(resolvePixelGeometry({ size, strokeWidth, absoluteStrokeWidth, pixelGap }));
  const pixelSize = $derived(pixelGeometry.pixelSize);
  const pixelInset = $derived(pixelGeometry.pixelInset);
  const normalizedShape = $derived(normalizeShape(shape));
  const normalizedRenderMode = $derived(normalizeRenderMode(renderMode));
  const roundedCornerRadius = $derived(Number(Math.min(0.24, Math.max(0, pixelSize / 2)).toFixed(3)));
  const optimizedPathData = $derived(
    resolveOptimizedPathData({
      iconPixels,
      iconRects,
      shape: normalizedShape,
      pixelSize,
      pixelInset
    })
  );
  const canRenderOptimized = $derived(optimizedPathData !== null);
  const shouldRenderOptimized = $derived(
    normalizedRenderMode !== 'raw' && canRenderOptimized
  );
</script>

<svg
  {...defaultAttributes}
  {...(!children && !title && !hasA11yProp(props) && { 'aria-hidden': 'true' })}
  {...props}
  width={size}
  height={size}
  class={['pxicons-icon lucide-icon lucide', name && ('lucide-' + name), name && ('pxicons-' + name), props.class]}
  shape-rendering="crispEdges"
>
  {#if title}
    <title>{title}</title>
  {/if}

  <g fill={color}>
    {#if shouldRenderOptimized}
      <path d={optimizedPathData ?? ''} />
    {:else if normalizedShape === 'circle'}
      {#each iconPixels as [x, y]}
        <circle
          cx={x + pixelInset + pixelSize / 2}
          cy={y + pixelInset + pixelSize / 2}
          r={pixelSize / 2}
        />
      {/each}
    {:else if normalizedShape === 'rounded'}
      {#each iconPixels as [x, y]}
        <rect
          x={x + pixelInset}
          y={y + pixelInset}
          width={pixelSize}
          height={pixelSize}
          rx={roundedCornerRadius}
          ry={roundedCornerRadius}
        />
      {/each}
    {:else}
      {#each iconPixels as [x, y]}
        <rect x={x + pixelInset} y={y + pixelInset} width={pixelSize} height={pixelSize} />
      {/each}
    {/if}
  </g>

  {@render children?.()}
</svg>
`;
}

function createLucideIndexFile() {
  return `${GENERATED_HEADER}
export * from './icons/index.js';
export * as icons from './icons/index.js';
export { default as defaultAttributes } from './default-attributes.js';
export { default as Icon } from './Icon.svelte';
export { resolveOptimizedPathData, normalizeRenderMode, normalizeShape } from './pixel-path.js';
export { resolvePixelGeometry } from './pixel-stroke.js';
export type {
  IconEvents,
  IconProps,
  IconSlots,
  IconPixels,
  IconRects,
  PixelCell,
  PixelRect,
  PixelShape,
  IconRenderMode
} from './types.js';
`;
}

function createIconComponentFile(iconId, iconPixels, iconRects) {
  const pixelsLiteral = JSON.stringify(iconPixels);
  const rectsLiteral = JSON.stringify(iconRects);

  return `<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = ${pixelsLiteral};
  const iconRects: IconRects = ${rectsLiteral};
</script>

<Icon name="${iconId}" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
`;
}

function createIconWrapperFile(iconId) {
  return `${GENERATED_HEADER}
export { default } from './${iconId}.svelte';
`;
}

function createIconsIndexFile(entries) {
  const exportLines = entries
    .map(({ componentName, iconId }) => `export { default as ${componentName} } from './${iconId}.svelte';`)
    .join('\n');

  return `${GENERATED_HEADER}
${exportLines}
`;
}

async function ensureEmptyDirectory(dirPath) {
  await fs.rm(dirPath, { recursive: true, force: true });
  await fs.mkdir(dirPath, { recursive: true });
}

async function writeFile(filePath, content) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

async function main() {
  const [manifest, pixelMap] = await Promise.all([loadManifest(), loadPixelMap()]);

  await ensureEmptyDirectory(iconsOutputDir);
  await ensureEmptyDirectory(utilsOutputDir);

  const entries = [];
  const seenNames = new Set();

  for (const item of manifest) {
    const iconId = item?.id;

    if (!iconId) {
      continue;
    }

    const iconPixels = pixelMap[iconId];

    if (!Array.isArray(iconPixels) || iconPixels.length === 0) {
      throw new Error(`Missing pixel map for icon id: ${iconId}`);
    }

    const iconRects = toRectRuns(iconPixels);
    const componentName = toPascalCase(iconId);

    if (!componentName) {
      throw new Error(`Could not generate component name for icon id: ${iconId}`);
    }

    if (seenNames.has(componentName)) {
      throw new Error(`Duplicate component name generated: ${componentName}`);
    }

    seenNames.add(componentName);
    entries.push({ iconId, componentName, iconPixels, iconRects });

    await writeFile(
      path.join(iconsOutputDir, `${iconId}.svelte`),
      createIconComponentFile(iconId, iconPixels, iconRects)
    );

    await writeFile(path.join(iconsOutputDir, `${iconId}.ts`), createIconWrapperFile(iconId));
  }

  await writeFile(path.join(outputDir, 'types.ts'), createTypesFile());
  await writeFile(path.join(outputDir, 'default-attributes.ts'), createDefaultAttributesFile());
  await writeFile(path.join(outputDir, 'pixel-stroke.ts'), createPixelStrokeFile());
  await writeFile(path.join(outputDir, 'pixel-path.ts'), createPixelPathFile());
  await writeFile(path.join(utilsOutputDir, 'hasA11yProp.ts'), createHasA11yPropFile());
  await writeFile(path.join(outputDir, 'Icon.svelte'), createIconBaseFile());
  await writeFile(path.join(outputDir, 'index.ts'), createLucideIndexFile());
  await writeFile(path.join(iconsOutputDir, 'index.ts'), createIconsIndexFile(entries));

  console.log(`Generated ${entries.length} Lucide Svelte icon components.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
