import { promises as fs } from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageDir = path.resolve(__dirname, '..');
const sourceDir = path.resolve(packageDir, '../../icons/lucide/src');
const outputDir = path.join(packageDir, 'src/lucide');
const iconsOutputDir = path.join(outputDir, 'icons');
const utilsOutputDir = path.join(outputDir, 'utils');

const GENERATED_HEADER = '// This file is auto-generated by scripts/generate-lucide.mjs.\n';

function evaluateTsModule(source, exportName) {
  const module = { exports: {} };
  const context = vm.createContext({ module, exports: module.exports, Object, Array, String, Number, Boolean });
  const script = new vm.Script(`${source}\nmodule.exports = { ${exportName} };`);
  script.runInContext(context);
  return module.exports[exportName];
}

async function loadManifest() {
  const manifestPath = path.join(sourceDir, 'icon-manifest.ts');
  let source = await fs.readFile(manifestPath, 'utf8');

  source = source
    .replace(/export interface[\s\S]*?}\n\n/g, '')
    .replace(/export type[^\n]*\n/g, '')
    .replace(/export const iconManifest\s*:[^=]+=/, 'const iconManifest =');

  const manifest = evaluateTsModule(source, 'iconManifest');

  if (!Array.isArray(manifest)) {
    throw new Error('Could not parse iconManifest from @pxicons/lucide.');
  }

  return manifest;
}

async function loadPixelMap() {
  const pixelMapPath = path.join(sourceDir, 'pixel-map.ts');
  let source = await fs.readFile(pixelMapPath, 'utf8');

  source = source
    .replace(/export type[^\n]*\n/g, '')
    .replace(/export const lucidePixelMap\s*:[^=]+=/, 'const lucidePixelMap =');

  const pixelMap = evaluateTsModule(source, 'lucidePixelMap');

  if (!pixelMap || typeof pixelMap !== 'object') {
    throw new Error('Could not parse lucidePixelMap from @pxicons/lucide.');
  }

  return pixelMap;
}

function toPascalCase(iconId) {
  return iconId
    .split('-')
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join('');
}

function createTypesFile() {
  return `${GENERATED_HEADER}
import type { Snippet } from 'svelte';
import type { SVGAttributes, SvelteHTMLElements } from 'svelte/elements';

export type PixelCell = readonly [number, number];
export type IconPixels = readonly PixelCell[];

export interface IconProps extends SVGAttributes<SVGSVGElement> {
  name?: string;
  color?: string;
  size?: number | string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
  iconPixels?: IconPixels;
  children?: Snippet;
  title?: string;
}

export type IconEvents = {
  [evt: string]: CustomEvent<any>;
};

export type IconSlots = {
  default: {};
};

export type PixelTag = keyof SvelteHTMLElements;
`;
}

function createDefaultAttributesFile() {
  return `${GENERATED_HEADER}
const defaultAttributes = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'none'
} as const;

export default defaultAttributes;
`;
}

function createPixelStrokeFile() {
  return `${GENERATED_HEADER}
export interface PixelGeometryOptions {
  size?: number | string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
}

export interface PixelGeometry {
  pixelSize: number;
  pixelInset: number;
}

export function resolvePixelGeometry(options: PixelGeometryOptions): PixelGeometry {
  const strokeWidth = options.strokeWidth ?? 2;
  const size = options.size ?? 24;
  const absoluteStrokeWidth = options.absoluteStrokeWidth ?? false;

  const parsedStrokeWidth = Number(strokeWidth);
  const safeStrokeWidth = Number.isFinite(parsedStrokeWidth) ? parsedStrokeWidth : 2;

  const parsedSize = Number(size);
  const hasNumericSize = Number.isFinite(parsedSize) && parsedSize > 0;

  const effectiveStrokeWidth =
    absoluteStrokeWidth && hasNumericSize
      ? (safeStrokeWidth * 24) / parsedSize
      : safeStrokeWidth;

  const pixelSize = Number(Math.max(0.05, effectiveStrokeWidth / 2).toFixed(3));
  const pixelInset = Number(((1 - pixelSize) / 2).toFixed(3));

  return { pixelSize, pixelInset };
}
`;
}

function createHasA11yPropFile() {
  return `${GENERATED_HEADER}
const A11Y_ATTRIBUTES = [
  'aria-label',
  'aria-labelledby',
  'aria-describedby',
  'role',
  'aria-hidden'
] as const;

export function hasA11yProp(props: Record<string, unknown>): boolean {
  return A11Y_ATTRIBUTES.some((attribute) => {
    const value = props[attribute];

    if (value === undefined || value === null) {
      return false;
    }

    if (typeof value === 'boolean') {
      return value;
    }

    if (typeof value === 'string') {
      return value.trim().length > 0;
    }

    return true;
  });
}
`;
}

function createIconBaseFile() {
  return `<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import defaultAttributes from './default-attributes.js';
  import { resolvePixelGeometry } from './pixel-stroke.js';
  import { hasA11yProp } from './utils/hasA11yProp.js';
  import type { IconProps } from './types.js';

  let {
    name,
    color = 'currentColor',
    size = 24,
    strokeWidth = 2,
    absoluteStrokeWidth = false,
    iconPixels = [],
    children,
    title,
    ...props
  }: IconProps = $props();

  const pixelGeometry = $derived(resolvePixelGeometry({ size, strokeWidth, absoluteStrokeWidth }));
  const pixelSize = $derived(pixelGeometry.pixelSize);
  const pixelInset = $derived(pixelGeometry.pixelInset);
</script>

<svg
  {...defaultAttributes}
  {...(!children && !title && !hasA11yProp(props) && { 'aria-hidden': 'true' })}
  {...props}
  width={size}
  height={size}
  class={['pxicons-icon lucide-icon lucide', name && ('lucide-' + name), name && ('pxicons-' + name), props.class]}
  shape-rendering="crispEdges"
>
  {#if title}
    <title>{title}</title>
  {/if}

  <g fill={color}>
    {#each iconPixels as [x, y]}
      <rect x={x + pixelInset} y={y + pixelInset} width={pixelSize} height={pixelSize} />
    {/each}
  </g>

  {@render children?.()}
</svg>
`;
}

function createLucideIndexFile() {
  return `${GENERATED_HEADER}
export * from './icons/index.js';
export * as icons from './icons/index.js';
export { default as defaultAttributes } from './default-attributes.js';
export { default as Icon } from './Icon.svelte';
export { resolvePixelGeometry } from './pixel-stroke.js';
export type { IconEvents, IconProps, IconSlots, IconPixels, PixelCell } from './types.js';
`;
}

function createIconComponentFile(iconId, iconPixels) {
  const pixelsLiteral = JSON.stringify(iconPixels);

  return `<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = ${pixelsLiteral};
</script>

<Icon name="${iconId}" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
`;
}

function createIconWrapperFile(iconId) {
  return `${GENERATED_HEADER}
export { default } from './${iconId}.svelte';
`;
}

function createIconsIndexFile(entries) {
  const exportLines = entries
    .map(({ componentName, iconId }) => `export { default as ${componentName} } from './${iconId}.svelte';`)
    .join('\n');

  return `${GENERATED_HEADER}
${exportLines}
`;
}

async function ensureEmptyDirectory(dirPath) {
  await fs.rm(dirPath, { recursive: true, force: true });
  await fs.mkdir(dirPath, { recursive: true });
}

async function writeFile(filePath, content) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

async function main() {
  const [manifest, pixelMap] = await Promise.all([loadManifest(), loadPixelMap()]);

  await ensureEmptyDirectory(iconsOutputDir);
  await ensureEmptyDirectory(utilsOutputDir);

  const entries = [];
  const seenNames = new Set();

  for (const item of manifest) {
    const iconId = item?.id;

    if (!iconId) {
      continue;
    }

    const iconPixels = pixelMap[iconId];

    if (!Array.isArray(iconPixels) || iconPixels.length === 0) {
      throw new Error(`Missing pixel map for icon id: ${iconId}`);
    }

    const componentName = toPascalCase(iconId);

    if (!componentName) {
      throw new Error(`Could not generate component name for icon id: ${iconId}`);
    }

    if (seenNames.has(componentName)) {
      throw new Error(`Duplicate component name generated: ${componentName}`);
    }

    seenNames.add(componentName);
    entries.push({ iconId, componentName, iconPixels });

    await writeFile(
      path.join(iconsOutputDir, `${iconId}.svelte`),
      createIconComponentFile(iconId, iconPixels)
    );

    await writeFile(path.join(iconsOutputDir, `${iconId}.ts`), createIconWrapperFile(iconId));
  }

  await writeFile(path.join(outputDir, 'types.ts'), createTypesFile());
  await writeFile(path.join(outputDir, 'default-attributes.ts'), createDefaultAttributesFile());
  await writeFile(path.join(outputDir, 'pixel-stroke.ts'), createPixelStrokeFile());
  await writeFile(path.join(utilsOutputDir, 'hasA11yProp.ts'), createHasA11yPropFile());
  await writeFile(path.join(outputDir, 'Icon.svelte'), createIconBaseFile());
  await writeFile(path.join(outputDir, 'index.ts'), createLucideIndexFile());
  await writeFile(path.join(iconsOutputDir, 'index.ts'), createIconsIndexFile(entries));

  console.log(`Generated ${entries.length} Lucide Svelte icon components.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
