import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateLucideEntries } from '../../../../tools/lucide-generator/index.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageDir = path.resolve(__dirname, '..');
const lucideDir = path.resolve(packageDir, '../../icons/lucide');
const outputDir = path.join(packageDir, 'src/lucide');
const iconsOutputDir = path.join(outputDir, 'icons');
const utilsOutputDir = path.join(outputDir, 'utils');

const GENERATED_HEADER = '// This file is auto-generated by scripts/generate-lucide.mjs.\n';

function createTypesFile() {
  return `${GENERATED_HEADER}
import type { Snippet } from 'svelte';
import type { SVGAttributes, SvelteHTMLElements } from 'svelte/elements';

export type PixelCell = readonly [number, number];
export type PixelRect = readonly [number, number, number, number];
export type IconPixels = readonly PixelCell[];
export type IconRects = readonly PixelRect[];
export type PixelShape = 'square' | 'circle' | 'rounded';
export type IconRenderMode = 'auto' | 'raw' | 'optimized';

export interface IconProps extends SVGAttributes<SVGSVGElement> {
  name?: string;
  color?: string;
  size?: number | string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
  shape?: PixelShape;
  renderMode?: IconRenderMode;
  iconPixels?: IconPixels;
  iconRects?: IconRects;
  children?: Snippet;
  title?: string;
}

export type IconEvents = {
  [evt: string]: CustomEvent<any>;
};

export type IconSlots = {
  default: {};
};

export type PixelTag = keyof SvelteHTMLElements;
`;
}

function createDefaultAttributesFile() {
  return `${GENERATED_HEADER}
const defaultAttributes = {
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: '0 0 24 24',
  fill: 'none'
} as const;

export default defaultAttributes;
`;
}

function createPixelStrokeFile() {
  return `${GENERATED_HEADER}
export { resolvePixelGeometry } from '@pxicons/lucide-core';
export type { PixelGeometry, PixelGeometryOptions } from '@pxicons/lucide-core';
`;
}

function createPixelPathFile() {
  return `${GENERATED_HEADER}
export {
  normalizeRenderMode,
  normalizeShape,
  resolveOptimizedPathData
} from '@pxicons/lucide-core';
export type { OptimizedPathOptions } from '@pxicons/lucide-core';
`;
}

function createHasA11yPropFile() {
  return `${GENERATED_HEADER}
export { hasA11yProp } from '@pxicons/lucide-core';
`;
}

function createIconBaseFile() {
  return `<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import defaultAttributes from './default-attributes.js';
  import { resolveOptimizedPathData, normalizeRenderMode, normalizeShape } from './pixel-path.js';
  import { resolvePixelGeometry } from './pixel-stroke.js';
  import { hasA11yProp } from './utils/hasA11yProp.js';
  import type { IconProps } from './types.js';

  let {
    name,
    color = 'currentColor',
    size = 24,
    strokeWidth = 2,
    absoluteStrokeWidth = false,
    shape = 'square',
    renderMode = 'auto',
    iconPixels = [],
    iconRects = [],
    children,
    title,
    ...props
  }: IconProps = $props();

  const pixelGeometry = $derived(resolvePixelGeometry({ size, strokeWidth, absoluteStrokeWidth }));
  const pixelSize = $derived(pixelGeometry.pixelSize);
  const pixelInset = $derived(pixelGeometry.pixelInset);
  const normalizedShape = $derived(normalizeShape(shape));
  const normalizedRenderMode = $derived(normalizeRenderMode(renderMode));
  const roundedCornerRadius = $derived(Number(Math.min(0.24, Math.max(0, pixelSize / 2)).toFixed(3)));
  const optimizedPathData = $derived(
    resolveOptimizedPathData({
      iconPixels,
      iconRects,
      shape: normalizedShape,
      pixelSize,
      pixelInset
    })
  );
  const canRenderOptimized = $derived(optimizedPathData !== null);
  const shouldRenderOptimized = $derived(
    normalizedRenderMode !== 'raw' && canRenderOptimized
  );
</script>

<svg
  {...defaultAttributes}
  {...(!children && !title && !hasA11yProp(props) && { 'aria-hidden': 'true' })}
  {...props}
  width={size}
  height={size}
  class={['pxicons-icon lucide-icon lucide', name && ('lucide-' + name), name && ('pxicons-' + name), props.class]}
  shape-rendering="crispEdges"
>
  {#if title}
    <title>{title}</title>
  {/if}

  <g fill={color}>
    {#if shouldRenderOptimized}
      <path d={optimizedPathData ?? ''} />
    {:else if normalizedShape === 'circle'}
      {#each iconPixels as [x, y]}
        <circle
          cx={x + pixelInset + pixelSize / 2}
          cy={y + pixelInset + pixelSize / 2}
          r={pixelSize / 2}
        />
      {/each}
    {:else if normalizedShape === 'rounded'}
      {#each iconPixels as [x, y]}
        <rect
          x={x + pixelInset}
          y={y + pixelInset}
          width={pixelSize}
          height={pixelSize}
          rx={roundedCornerRadius}
          ry={roundedCornerRadius}
        />
      {/each}
    {:else}
      {#each iconPixels as [x, y]}
        <rect x={x + pixelInset} y={y + pixelInset} width={pixelSize} height={pixelSize} />
      {/each}
    {/if}
  </g>

  {@render children?.()}
</svg>
`;
}

function createLucideIndexFile() {
  return `${GENERATED_HEADER}
export * from './icons/index.js';
export * as icons from './icons/index.js';
export { default as defaultAttributes } from './default-attributes.js';
export { default as Icon } from './Icon.svelte';
export { resolveOptimizedPathData, normalizeRenderMode, normalizeShape } from './pixel-path.js';
export { resolvePixelGeometry } from './pixel-stroke.js';
export type {
  IconEvents,
  IconProps,
  IconSlots,
  IconPixels,
  IconRects,
  PixelCell,
  PixelRect,
  PixelShape,
  IconRenderMode
} from './types.js';
`;
}

function createIconComponentFile(iconId, iconPixels, iconRects) {
  const pixelsLiteral = JSON.stringify(iconPixels);
  const rectsLiteral = JSON.stringify(iconRects);

  return `<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = ${pixelsLiteral};
  const iconRects: IconRects = ${rectsLiteral};
</script>

<Icon name="${iconId}" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
`;
}

function createIconWrapperFile(iconId) {
  return `${GENERATED_HEADER}
export { default } from './${iconId}.svelte';
`;
}

function createIconsIndexFile(entries) {
  const exportLines = entries
    .map(({ componentName, iconId }) => `export { default as ${componentName} } from './${iconId}.svelte';`)
    .join('\n');

  return `${GENERATED_HEADER}
${exportLines}
`;
}

async function ensureEmptyDirectory(dirPath) {
  await fs.rm(dirPath, { recursive: true, force: true });
  await fs.mkdir(dirPath, { recursive: true });
}

async function writeFile(filePath, content) {
  await fs.mkdir(path.dirname(filePath), { recursive: true });
  await fs.writeFile(filePath, content, 'utf8');
}

async function main() {
  const entries = await generateLucideEntries(lucideDir);

  await ensureEmptyDirectory(iconsOutputDir);
  await ensureEmptyDirectory(utilsOutputDir);

  for (const { iconId, iconPixels, iconRects } of entries) {
    await writeFile(
      path.join(iconsOutputDir, `${iconId}.svelte`),
      createIconComponentFile(iconId, iconPixels, iconRects)
    );

    await writeFile(path.join(iconsOutputDir, `${iconId}.ts`), createIconWrapperFile(iconId));
  }

  await writeFile(path.join(outputDir, 'types.ts'), createTypesFile());
  await writeFile(path.join(outputDir, 'default-attributes.ts'), createDefaultAttributesFile());
  await writeFile(path.join(outputDir, 'pixel-stroke.ts'), createPixelStrokeFile());
  await writeFile(path.join(outputDir, 'pixel-path.ts'), createPixelPathFile());
  await writeFile(path.join(utilsOutputDir, 'hasA11yProp.ts'), createHasA11yPropFile());
  await writeFile(path.join(outputDir, 'Icon.svelte'), createIconBaseFile());
  await writeFile(path.join(outputDir, 'index.ts'), createLucideIndexFile());
  await writeFile(path.join(iconsOutputDir, 'index.ts'), createIconsIndexFile(entries));

  console.log(`Generated ${entries.length} Lucide Svelte icon components.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
