export interface PixelIconManifestEntry {
  id: string;
  name: string;
  tags: readonly string[];
}

export const iconManifest: readonly PixelIconManifestEntry[] = [
  { id: 'settings', name: 'Settings', tags: ['settings', 'gear', 'preferences', 'config', 'tools'] },
  { id: 'search', name: 'Search', tags: ['search', 'magnifier', 'find', 'lookup'] },
  { id: 'home', name: 'Home', tags: ['home', 'house', 'dashboard'] },
  { id: 'user', name: 'User', tags: ['user', 'profile', 'account', 'person'] },
  { id: 'users', name: 'Users', tags: ['users', 'team', 'group', 'accounts'] },
  { id: 'bell', name: 'Bell', tags: ['bell', 'notification', 'alert', 'ring'] },
  { id: 'heart', name: 'Heart', tags: ['heart', 'favorite', 'like', 'love'] },
  { id: 'star', name: 'Star', tags: ['star', 'favorite', 'bookmark', 'rating'] },
  { id: 'bookmark', name: 'Bookmark', tags: ['bookmark', 'save', 'favorite'] },
  { id: 'message-circle', name: 'Message Circle', tags: ['message-circle', 'message', 'circle', 'chat', 'comment'] },
  { id: 'mail', name: 'Mail', tags: ['mail', 'email', 'inbox', 'letter'] },
  { id: 'phone', name: 'Phone', tags: ['phone', 'call', 'contact', 'dial'] },
  { id: 'camera', name: 'Camera', tags: ['camera', 'photo', 'image', 'capture'] },
  { id: 'image', name: 'Image', tags: ['image', 'photo', 'picture', 'media'] },
  { id: 'play', name: 'Play', tags: ['play', 'start', 'media', 'video'] },
  { id: 'pause', name: 'Pause', tags: ['pause', 'media', 'hold'] },
  { id: 'stop-circle', name: 'Stop Circle', tags: ['stop-circle', 'stop', 'circle', 'media'] },
  { id: 'skip-forward', name: 'Skip Forward', tags: ['skip-forward', 'skip', 'forward', 'next', 'media'] },
  { id: 'skip-back', name: 'Skip Back', tags: ['skip-back', 'skip', 'back', 'previous', 'media'] },
  { id: 'volume-2', name: 'Volume 2', tags: ['volume-2', 'volume', '2', 'audio', 'sound', 'speaker'] },
  { id: 'volume-x', name: 'Volume X', tags: ['volume-x', 'volume', 'x', 'mute', 'audio', 'sound'] },
  { id: 'mic', name: 'Mic', tags: ['mic', 'audio', 'record', 'microphone'] },
  { id: 'mic-off', name: 'Mic Off', tags: ['mic-off', 'mic', 'off', 'mute', 'microphone'] },
  { id: 'lock', name: 'Lock', tags: ['lock', 'secure', 'privacy', 'password'] },
  { id: 'unlock', name: 'Unlock', tags: ['unlock', 'open', 'secure', 'privacy'] },
  { id: 'shield', name: 'Shield', tags: ['shield', 'security', 'protection', 'safe'] },
  { id: 'key', name: 'Key', tags: ['key', 'access', 'security'] },
  { id: 'trash-2', name: 'Trash 2', tags: ['trash-2', 'trash', '2', 'delete', 'remove', 'bin'] },
  { id: 'pencil', name: 'Pencil', tags: ['pencil', 'edit', 'write', 'draw'] },
  { id: 'plus', name: 'Plus', tags: ['plus', 'add', 'new', 'create'] },
  { id: 'minus', name: 'Minus', tags: ['minus', 'remove', 'subtract'] },
  { id: 'x', name: 'X', tags: ['x', 'close', 'dismiss', 'cancel'] },
  { id: 'check', name: 'Check', tags: ['check', 'confirm', 'done', 'success'] },
  { id: 'chevron-right', name: 'Chevron Right', tags: ['chevron-right', 'chevron', 'right', 'next', 'forward'] },
  { id: 'chevron-left', name: 'Chevron Left', tags: ['chevron-left', 'chevron', 'left', 'previous', 'back'] },
  { id: 'chevron-up', name: 'Chevron Up', tags: ['chevron-up', 'chevron', 'up', 'expand'] },
  { id: 'chevron-down', name: 'Chevron Down', tags: ['chevron-down', 'chevron', 'down', 'collapse'] },
  { id: 'arrow-right', name: 'Arrow Right', tags: ['arrow-right', 'arrow', 'right', 'next', 'forward', 'direction'] },
  { id: 'arrow-left', name: 'Arrow Left', tags: ['arrow-left', 'arrow', 'left', 'back', 'previous', 'direction'] },
  { id: 'arrow-up', name: 'Arrow Up', tags: ['arrow-up', 'arrow', 'up', 'direction', 'top'] },
  { id: 'arrow-down', name: 'Arrow Down', tags: ['arrow-down', 'arrow', 'down', 'direction', 'bottom'] },
  { id: 'download', name: 'Download', tags: ['download', 'save', 'import'] },
  { id: 'upload', name: 'Upload', tags: ['upload', 'send', 'export'] },
  { id: 'share-2', name: 'Share 2', tags: ['share-2', 'share', '2', 'forward', 'external'] },
  { id: 'link', name: 'Link', tags: ['link', 'url', 'chain', 'connect'] },
  { id: 'copy', name: 'Copy', tags: ['copy', 'duplicate', 'clone'] },
  { id: 'external-link', name: 'External Link', tags: ['external-link', 'external', 'link', 'open', 'outbound', 'url'] },
  { id: 'menu', name: 'Menu', tags: ['menu', 'navigation', 'hamburger'] },
  { id: 'grid-3x3', name: 'Grid 3x3', tags: ['grid-3x3', 'grid', '3x3', 'layout', 'apps', 'tiles'] },
  { id: 'list', name: 'List', tags: ['list', 'rows', 'items', 'menu'] },
  { id: 'calendar', name: 'Calendar', tags: ['calendar', 'date', 'schedule', 'event'] },
  { id: 'clock-3', name: 'Clock 3', tags: ['clock-3', 'clock', '3', 'time', 'watch'] },
  { id: 'map-pin', name: 'Map Pin', tags: ['map-pin', 'map', 'pin', 'location', 'place'] },
  { id: 'globe', name: 'Globe', tags: ['globe', 'world', 'internet', 'web'] },
  { id: 'wifi', name: 'Wifi', tags: ['wifi', 'network', 'internet', 'signal'] },
  { id: 'bluetooth', name: 'Bluetooth', tags: ['bluetooth', 'wireless', 'connection'] },
  { id: 'battery', name: 'Battery', tags: ['battery', 'power', 'charge'] },
  { id: 'sun', name: 'Sun', tags: ['sun', 'light', 'day', 'brightness'] },
  { id: 'moon', name: 'Moon', tags: ['moon', 'night', 'dark', 'theme'] },
  { id: 'cloud', name: 'Cloud', tags: ['cloud', 'weather', 'storage'] },
  { id: 'cloud-rain', name: 'Cloud Rain', tags: ['cloud-rain', 'cloud', 'rain', 'weather'] },
  { id: 'folder', name: 'Folder', tags: ['folder', 'directory', 'files'] },
  { id: 'file', name: 'File', tags: ['file', 'document', 'paper'] },
  { id: 'terminal', name: 'Terminal', tags: ['terminal', 'shell', 'cli', 'console'] },
  { id: 'code', name: 'Code', tags: ['code', 'development', 'brackets'] },
  { id: 'github', name: 'Github', tags: ['github', 'git', 'repository', 'source-control'] },
];
