<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[14,1],[15,1],[14,2],[15,2],[15,3],[16,3],[10,4],[11,4],[15,4],[16,4],[17,4],[10,5],[11,5],[16,5],[17,5],[11,6],[12,6],[16,6],[17,6],[18,6],[11,7],[12,7],[17,7],[18,7],[12,8],[13,8],[7,9],[8,9],[12,9],[13,9],[7,10],[8,10],[8,11],[9,11],[8,12],[9,12],[8,13],[9,13],[10,13],[4,14],[5,14],[9,14],[10,14],[4,15],[5,15],[5,16],[6,16],[5,17],[6,17],[6,18],[7,18],[6,19],[7,19]];
</script>

<Icon name="candy-cane" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
