<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[19,5],[20,5],[18,6],[19,6],[20,6],[17,7],[18,7],[19,7],[16,8],[17,8],[18,8],[15,9],[16,9],[17,9],[14,10],[15,10],[16,10],[3,11],[4,11],[13,11],[14,11],[15,11],[3,12],[4,12],[5,12],[12,12],[13,12],[14,12],[4,13],[5,13],[6,13],[11,13],[12,13],[13,13],[5,14],[6,14],[7,14],[10,14],[11,14],[12,14],[6,15],[7,15],[8,15],[9,15],[10,15],[11,15],[7,16],[8,16],[9,16],[10,16],[8,17],[9,17]];
</script>

<Icon name="check" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
