<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[6,5],[7,5],[16,5],[17,5],[6,6],[7,6],[15,6],[16,6],[17,6],[6,7],[7,7],[14,7],[15,7],[16,7],[6,8],[7,8],[13,8],[14,8],[15,8],[6,9],[7,9],[12,9],[13,9],[14,9],[6,10],[7,10],[11,10],[12,10],[13,10],[6,11],[7,11],[10,11],[11,11],[12,11],[6,12],[7,12],[10,12],[11,12],[12,12],[6,13],[7,13],[11,13],[12,13],[13,13],[6,14],[7,14],[12,14],[13,14],[14,14],[6,15],[7,15],[13,15],[14,15],[15,15],[6,16],[7,16],[14,16],[15,16],[16,16],[6,17],[7,17],[15,17],[16,17],[17,17],[6,18],[7,18],[16,18],[17,18]];
</script>

<Icon name="chevron-first" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
