<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[6,5],[7,5],[16,5],[17,5],[6,6],[7,6],[8,6],[16,6],[17,6],[7,7],[8,7],[9,7],[16,7],[17,7],[8,8],[9,8],[10,8],[16,8],[17,8],[9,9],[10,9],[11,9],[16,9],[17,9],[10,10],[11,10],[12,10],[16,10],[17,10],[11,11],[12,11],[13,11],[16,11],[17,11],[11,12],[12,12],[13,12],[16,12],[17,12],[10,13],[11,13],[12,13],[16,13],[17,13],[9,14],[10,14],[11,14],[16,14],[17,14],[8,15],[9,15],[10,15],[16,15],[17,15],[7,16],[8,16],[9,16],[16,16],[17,16],[6,17],[7,17],[8,17],[16,17],[17,17],[6,18],[7,18],[16,18],[17,18]];
</script>

<Icon name="chevron-last" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
