<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[8,6],[9,6],[14,6],[15,6],[7,7],[8,7],[9,7],[14,7],[15,7],[16,7],[6,8],[7,8],[8,8],[15,8],[16,8],[17,8],[5,9],[6,9],[7,9],[16,9],[17,9],[18,9],[4,10],[5,10],[6,10],[17,10],[18,10],[19,10],[3,11],[4,11],[5,11],[18,11],[19,11],[20,11],[3,12],[4,12],[5,12],[18,12],[19,12],[20,12],[4,13],[5,13],[6,13],[17,13],[18,13],[19,13],[5,14],[6,14],[7,14],[16,14],[17,14],[18,14],[6,15],[7,15],[8,15],[15,15],[16,15],[17,15],[7,16],[8,16],[9,16],[14,16],[15,16],[16,16],[8,17],[9,17],[14,17],[15,17]];
</script>

<Icon name="chevrons-left-right" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
