<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[8,5],[9,5],[8,6],[9,6],[10,6],[9,7],[10,7],[11,7],[10,8],[11,8],[12,8],[11,9],[12,9],[13,9],[12,10],[13,10],[14,10],[13,11],[14,11],[15,11],[13,12],[14,12],[15,12],[12,13],[13,13],[14,13],[11,14],[12,14],[13,14],[10,15],[11,15],[12,15],[9,16],[10,16],[11,16],[8,17],[9,17],[10,17],[8,18],[9,18]];
  const iconRects: IconRects = [[8,5,2,1],[8,6,3,1],[9,7,3,1],[10,8,3,1],[11,9,3,1],[12,10,3,1],[13,11,3,1],[13,12,3,1],[12,13,3,1],[11,14,3,1],[10,15,3,1],[9,16,3,1],[8,17,3,1],[8,18,2,1]];
</script>

<Icon name="chevron-right" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
