<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[3,6],[4,6],[19,6],[20,6],[3,7],[4,7],[5,7],[18,7],[19,7],[20,7],[4,8],[5,8],[6,8],[17,8],[18,8],[19,8],[5,9],[6,9],[7,9],[16,9],[17,9],[18,9],[6,10],[7,10],[8,10],[15,10],[16,10],[17,10],[7,11],[8,11],[9,11],[14,11],[15,11],[16,11],[7,12],[8,12],[9,12],[14,12],[15,12],[16,12],[6,13],[7,13],[8,13],[15,13],[16,13],[17,13],[5,14],[6,14],[7,14],[16,14],[17,14],[18,14],[4,15],[5,15],[6,15],[17,15],[18,15],[19,15],[3,16],[4,16],[5,16],[18,16],[19,16],[20,16],[3,17],[4,17],[19,17],[20,17]];
</script>

<Icon name="chevrons-right-left" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
