<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[14,5],[15,5],[13,6],[14,6],[15,6],[12,7],[13,7],[14,7],[11,8],[12,8],[13,8],[10,9],[11,9],[12,9],[9,10],[10,10],[11,10],[8,11],[9,11],[10,11],[8,12],[9,12],[10,12],[9,13],[10,13],[11,13],[10,14],[11,14],[12,14],[11,15],[12,15],[13,15],[12,16],[13,16],[14,16],[13,17],[14,17],[15,17],[14,18],[15,18]];
</script>

<Icon name="chevron-left" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
