<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[5,8],[6,8],[17,8],[18,8],[5,9],[6,9],[7,9],[16,9],[17,9],[18,9],[6,10],[7,10],[8,10],[15,10],[16,10],[17,10],[7,11],[8,11],[9,11],[14,11],[15,11],[16,11],[8,12],[9,12],[10,12],[13,12],[14,12],[15,12],[9,13],[10,13],[11,13],[12,13],[13,13],[14,13],[10,14],[11,14],[12,14],[13,14],[11,15],[12,15]];
</script>

<Icon name="chevron-down" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
