<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[10,6],[11,6],[17,6],[18,6],[9,7],[10,7],[11,7],[16,7],[17,7],[18,7],[8,8],[9,8],[10,8],[15,8],[16,8],[17,8],[7,9],[8,9],[9,9],[14,9],[15,9],[16,9],[6,10],[7,10],[8,10],[13,10],[14,10],[15,10],[5,11],[6,11],[7,11],[12,11],[13,11],[14,11],[5,12],[6,12],[7,12],[12,12],[13,12],[14,12],[6,13],[7,13],[8,13],[13,13],[14,13],[15,13],[7,14],[8,14],[9,14],[14,14],[15,14],[16,14],[8,15],[9,15],[10,15],[15,15],[16,15],[17,15],[9,16],[10,16],[11,16],[16,16],[17,16],[18,16],[10,17],[11,17],[17,17],[18,17]];
</script>

<Icon name="chevrons-left" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
