<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[11,8],[12,8],[10,9],[11,9],[12,9],[13,9],[9,10],[10,10],[11,10],[12,10],[13,10],[14,10],[8,11],[9,11],[10,11],[13,11],[14,11],[15,11],[7,12],[8,12],[9,12],[14,12],[15,12],[16,12],[6,13],[7,13],[8,13],[15,13],[16,13],[17,13],[5,14],[6,14],[7,14],[16,14],[17,14],[18,14],[5,15],[6,15],[17,15],[18,15]];
</script>

<Icon name="chevron-up" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
