<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[11,10],[12,10],[10,11],[11,11],[12,11],[13,11],[10,12],[11,12],[12,12],[13,12],[11,13],[12,13],[13,13]];
  const iconRects: IconRects = [[11,10,2,1],[10,11,4,1],[10,12,4,1],[11,13,3,1]];
</script>

<Icon name="dot" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
