<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[11,3],[12,3],[10,4],[11,4],[12,4],[13,4],[10,5],[11,5],[12,5],[13,5],[11,6],[12,6],[11,10],[12,10],[10,11],[11,11],[12,11],[13,11],[10,12],[11,12],[12,12],[13,12],[11,13],[12,13],[11,17],[12,17],[10,18],[11,18],[12,18],[13,18],[10,19],[11,19],[12,19],[13,19],[11,20],[12,20]];
</script>

<Icon name="ellipsis-vertical" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
