<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[4,10],[5,10],[11,10],[12,10],[18,10],[19,10],[3,11],[4,11],[5,11],[6,11],[10,11],[11,11],[12,11],[13,11],[17,11],[18,11],[19,11],[20,11],[3,12],[4,12],[5,12],[6,12],[10,12],[11,12],[12,12],[13,12],[17,12],[18,12],[19,12],[20,12],[4,13],[5,13],[11,13],[12,13],[18,13],[19,13]];
</script>

<Icon name="ellipsis" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
