<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[6,7],[7,7],[8,7],[9,7],[10,7],[4,8],[5,8],[6,8],[7,8],[8,8],[9,8],[10,8],[11,8],[12,8],[18,8],[19,8],[4,9],[5,9],[11,9],[12,9],[13,9],[14,9],[15,9],[16,9],[17,9],[18,9],[19,9],[13,10],[14,10],[15,10],[16,10],[17,10],[6,13],[7,13],[8,13],[9,13],[10,13],[4,14],[5,14],[6,14],[7,14],[8,14],[9,14],[10,14],[11,14],[12,14],[18,14],[19,14],[4,15],[5,15],[11,15],[12,15],[13,15],[14,15],[15,15],[16,15],[17,15],[18,15],[19,15],[13,16],[14,16],[15,16],[16,16],[17,16]];
  const iconRects: IconRects = [[6,7,5,1],[4,8,9,1],[18,8,2,1],[4,9,2,1],[11,9,9,1],[13,10,5,1],[6,13,5,1],[4,14,9,1],[18,14,2,1],[4,15,2,1],[11,15,9,1],[13,16,5,1]];
</script>

<Icon name="equal-approximately" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
