<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[11,2],[12,2],[11,3],[12,3],[11,4],[12,4],[11,5],[12,5],[11,6],[12,6],[11,7],[12,7],[10,8],[11,8],[12,8],[13,8],[9,9],[10,9],[11,9],[12,9],[13,9],[14,9],[8,10],[9,10],[10,10],[13,10],[14,10],[15,10],[8,11],[9,11],[14,11],[15,11],[8,12],[9,12],[14,12],[15,12],[8,13],[9,13],[10,13],[13,13],[14,13],[15,13],[9,14],[10,14],[11,14],[12,14],[13,14],[14,14],[10,15],[11,15],[12,15],[13,15],[11,16],[12,16],[11,17],[12,17],[11,18],[12,18],[11,19],[12,19],[11,20],[12,20],[11,21],[12,21]];
</script>

<Icon name="git-commit-vertical" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
