<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[4,4],[5,4],[6,4],[7,4],[8,4],[9,4],[10,4],[11,4],[4,5],[5,5],[6,5],[7,5],[8,5],[9,5],[10,5],[11,5],[4,6],[5,6],[6,6],[7,6],[8,6],[9,6],[4,7],[5,7],[6,7],[7,7],[8,7],[4,8],[5,8],[6,8],[7,8],[8,8],[9,8],[4,9],[5,9],[6,9],[8,9],[9,9],[10,9],[4,10],[5,10],[9,10],[10,10],[11,10],[4,11],[5,11],[10,11],[11,11],[12,11],[11,12],[12,12],[13,12],[12,13],[13,13],[14,13],[13,14],[14,14],[15,14],[14,15],[15,15],[16,15],[15,16],[16,16],[17,16],[16,17],[17,17],[18,17],[17,18],[18,18],[19,18],[18,19],[19,19]];
</script>

<Icon name="move-up-left" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
