<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[1,19],[2,19],[1,20],[2,20]];
</script>

<Icon name="signal-zero" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
