<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[1,19],[2,19],[1,20],[2,20]];
  const iconRects: IconRects = [[1,19,2,1],[1,20,2,1]];
</script>

<Icon name="signal-zero" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
