<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[11,11],[12,11],[11,12],[12,12],[11,13],[12,13],[11,14],[12,14],[6,15],[7,15],[11,15],[12,15],[6,16],[7,16],[11,16],[12,16],[6,17],[7,17],[11,17],[12,17],[6,18],[7,18],[11,18],[12,18],[1,19],[2,19],[6,19],[7,19],[11,19],[12,19],[1,20],[2,20],[6,20],[7,20],[11,20],[12,20]];
</script>

<Icon name="signal-medium" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
