<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[16,7],[17,7],[16,8],[17,8],[16,9],[17,9],[16,10],[17,10],[11,11],[12,11],[16,11],[17,11],[11,12],[12,12],[16,12],[17,12],[11,13],[12,13],[16,13],[17,13],[11,14],[12,14],[16,14],[17,14],[6,15],[7,15],[11,15],[12,15],[16,15],[17,15],[6,16],[7,16],[11,16],[12,16],[16,16],[17,16],[6,17],[7,17],[11,17],[12,17],[16,17],[17,17],[6,18],[7,18],[11,18],[12,18],[16,18],[17,18],[1,19],[2,19],[6,19],[7,19],[11,19],[12,19],[16,19],[17,19],[1,20],[2,20],[6,20],[7,20],[11,20],[12,20],[16,20],[17,20]];
</script>

<Icon name="signal-high" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
