<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[6,15],[7,15],[6,16],[7,16],[6,17],[7,17],[6,18],[7,18],[1,19],[2,19],[6,19],[7,19],[1,20],[2,20],[6,20],[7,20]];
</script>

<Icon name="signal-low" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
