<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[6,15],[7,15],[6,16],[7,16],[6,17],[7,17],[6,18],[7,18],[1,19],[2,19],[6,19],[7,19],[1,20],[2,20],[6,20],[7,20]];
  const iconRects: IconRects = [[6,15,2,1],[6,16,2,1],[6,17,2,1],[6,18,2,1],[1,19,2,1],[6,19,2,1],[1,20,2,1],[6,20,2,1]];
</script>

<Icon name="signal-low" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
