<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[21,1],[22,1],[20,2],[21,2],[22,2],[19,3],[20,3],[21,3],[18,4],[19,4],[20,4],[17,5],[18,5],[19,5],[16,6],[17,6],[18,6],[15,7],[16,7],[17,7],[14,8],[15,8],[16,8],[13,9],[14,9],[15,9],[12,10],[13,10],[14,10],[11,11],[12,11],[13,11],[10,12],[11,12],[12,12],[9,13],[10,13],[11,13],[8,14],[9,14],[10,14],[7,15],[8,15],[9,15],[6,16],[7,16],[8,16],[5,17],[6,17],[7,17],[4,18],[5,18],[6,18],[3,19],[4,19],[5,19],[2,20],[3,20],[4,20],[1,21],[2,21],[3,21],[1,22],[2,22]];
</script>

<Icon name="slash" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
