<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[3,3],[4,3],[3,4],[4,4],[3,5],[4,5],[3,6],[4,6],[3,7],[4,7],[3,8],[4,8],[3,9],[4,9],[3,10],[4,10],[3,11],[4,11],[3,12],[4,12],[3,13],[4,13],[3,14],[4,14],[3,15],[4,15],[3,16],[4,16],[3,17],[4,17],[3,18],[4,18],[3,19],[4,19],[3,20],[4,20]];
</script>

<Icon name="tally-1" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
