<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[3,3],[4,3],[8,3],[9,3],[3,4],[4,4],[8,4],[9,4],[3,5],[4,5],[8,5],[9,5],[3,6],[4,6],[8,6],[9,6],[3,7],[4,7],[8,7],[9,7],[3,8],[4,8],[8,8],[9,8],[3,9],[4,9],[8,9],[9,9],[3,10],[4,10],[8,10],[9,10],[3,11],[4,11],[8,11],[9,11],[3,12],[4,12],[8,12],[9,12],[3,13],[4,13],[8,13],[9,13],[3,14],[4,14],[8,14],[9,14],[3,15],[4,15],[8,15],[9,15],[3,16],[4,16],[8,16],[9,16],[3,17],[4,17],[8,17],[9,17],[3,18],[4,18],[8,18],[9,18],[3,19],[4,19],[8,19],[9,19],[3,20],[4,20],[8,20],[9,20]];
</script>

<Icon name="tally-2" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
