<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[3,4],[4,4],[3,5],[4,5],[5,5],[4,6],[5,6],[6,6],[5,7],[6,7],[7,7],[6,8],[7,8],[8,8],[7,9],[8,9],[9,9],[8,10],[9,10],[10,10],[8,11],[9,11],[10,11],[7,12],[8,12],[9,12],[6,13],[7,13],[8,13],[5,14],[6,14],[7,14],[4,15],[5,15],[6,15],[3,16],[4,16],[5,16],[3,17],[4,17],[11,18],[12,18],[13,18],[14,18],[15,18],[16,18],[17,18],[18,18],[19,18],[20,18],[11,19],[12,19],[13,19],[14,19],[15,19],[16,19],[17,19],[18,19],[19,19],[20,19]];
</script>

<Icon name="terminal" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
