<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[10,14],[11,14],[12,14],[13,14],[8,15],[9,15],[10,15],[11,15],[12,15],[13,15],[14,15],[15,15],[7,16],[8,16],[9,16],[14,16],[15,16],[16,16],[11,19],[12,19],[11,20],[12,20]];
  const iconRects: IconRects = [[10,14,4,1],[8,15,8,1],[7,16,3,1],[14,16,3,1],[11,19,2,1],[11,20,2,1]];
</script>

<Icon name="wifi-low" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
