<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[9,9],[10,9],[11,9],[12,9],[13,9],[14,9],[6,10],[7,10],[8,10],[9,10],[10,10],[11,10],[12,10],[13,10],[14,10],[15,10],[16,10],[17,10],[5,11],[6,11],[7,11],[8,11],[15,11],[16,11],[17,11],[18,11],[4,12],[5,12],[6,12],[17,12],[18,12],[19,12],[4,13],[5,13],[18,13],[19,13],[10,14],[11,14],[12,14],[13,14],[8,15],[9,15],[10,15],[11,15],[12,15],[13,15],[14,15],[15,15],[7,16],[8,16],[9,16],[14,16],[15,16],[16,16],[11,19],[12,19],[11,20],[12,20]];
</script>

<Icon name="wifi-high" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
