<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[11,19],[12,19],[11,20],[12,20]];
  const iconRects: IconRects = [[11,19,2,1],[11,20,2,1]];
</script>

<Icon name="wifi-zero" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
