<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[10,14],[11,14],[12,14],[13,14],[8,15],[9,15],[10,15],[11,15],[12,15],[13,15],[14,15],[15,15],[7,16],[8,16],[9,16],[14,16],[15,16],[16,16],[11,19],[12,19],[11,20],[12,20]];
</script>

<Icon name="wifi-low" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
