<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[18,11],[19,11],[18,12],[19,12],[17,13],[18,13],[17,14],[18,14],[17,15],[19,18],[20,18],[19,19],[20,19],[21,19],[22,19],[21,20],[22,20]];
</script>

<Icon name="worm" {...props} iconPixels={iconPixels}>
  {@render props.children?.()}
</Icon>
