<script lang="ts">
  // This file is auto-generated by scripts/generate-lucide.mjs.
  import Icon from '../Icon.svelte';
  import type { IconProps, IconPixels, IconRects } from '../types.js';

  let props: IconProps = $props();
  const iconPixels: IconPixels = [[18,11],[19,11],[18,12],[19,12],[17,13],[18,13],[17,14],[18,14],[17,15],[19,18],[20,18],[19,19],[20,19],[21,19],[22,19],[21,20],[22,20]];
  const iconRects: IconRects = [[18,11,2,1],[18,12,2,1],[17,13,2,1],[17,14,2,1],[17,15,1,1],[19,18,2,1],[19,19,4,1],[21,20,2,1]];
</script>

<Icon name="worm" {...props} iconPixels={iconPixels} iconRects={iconRects}>
  {@render props.children?.()}
</Icon>
